rails6-bookers2-debug-ruby3-main/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get 'search' => 'searches#search'
  get 'sort_books', to: 'books#sort_by_likes', defaults: { format: :js }

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :chat_rooms, only: [:show] do
    resources :chat_messages, only: [:create]
  end
end

rails6-bookers2-debug-ruby3-main/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  scope :with_recent_favorites_count, -> {
    left_joins(:favorites)
         .group('books.id')
         .order('COUNT(favorites.id) DESC, books.created_at DESC')
  }
end

rails6-bookers2-debug-ruby3-main/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @books_comment = BookComment.new
    @book.increment!(:views_count)
  end

  def index
    @books = Book.with_recent_favorites_count
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      flash.now[:error] = @book.errors.full_messages.join('/')
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      flash.now[:error] = @book.errors.full_messages.join('/')
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "Book was successfully deleted."
  end
  
  def sort_by_likes
   @books = Book.with_recent_favorites_count
    respond_to do |format|
      format.js { render 'index' }
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path, alert: "You are not authorized to edit this book."
    end
  end
end

rails6-bookers2-debug-ruby3-main/app/helpers/books_helper.rb
module BooksHelper
end

rails6-bookers2-debug-ruby3-main/app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails6-bookers2-debug-ruby3-main/app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title, book %></td>
        <td><%= book.body %></td>
        <td class="favorite-btn" data-book-id="<%= book.id %>">
          <%= render 'favorites/favorite_btn', book: book %>
        </td>
        <td>
          <p>コメント数: <%= book.book_comments.count %></p>
        </td>
        <td>
          <p>閲覧数 : <%= book.views_count %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

rails6-bookers2-debug-ruby3-main/app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <% if flash.now[:error] %>
        <div class="alert alert-danger">
          <%= "error" + flash.now[:error] %>
        </div>
      <% end %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

rails6-bookers2-debug-ruby3-main/app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
   <% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% end %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      
      <div id="books-list">
        <%= render 'index', books: @books %>
      </div>
    </div>
  </div>
</div>

rails6-bookers2-debug-ruby3-main/app/views/books/index.js.erb
$("#books-list").html("<%= j render 'index', books: @books %>");

rails6-bookers2-debug-ruby3-main/app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td>
            <%= link_to(@book.user) do %>
              <%= image_tag @book.user.get_profile_image, size: "100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <% if current_user.favorites.exists?(book_id: @book.id) %>
              <%= link_to '♡', book_favorite_path(@book), method: :delete, class: 'favorite-icon', style: 'color: red;' %>
              <span class="favorite-icon" style="color: red;"><%= @book.favorites.count %></span>
            <% else %>
              <%= link_to '♡', book_favorite_path(@book), method: :post, class: 'not-favorite-icon', style: 'color: blue;' %>
              <span class="not-favorite-icon" style="color: blue;"><%= @book.favorites.count %></span>
            <% end %>
          </td>
          <td>
            <p>コメント数: <%= @book.book_comments.count %></p>
          </td>
          <% if current_user.id == @book.user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      
      <% @book.book_comments.each do |comment| %>
        <div class="row mb-2" style="padding: 12px;">
          <div class="col-md-3">
            <%= link_to(comment.user) do %>
              <%= image_tag comment.user.get_profile_image, size: "100x100" %><br>
              <%= comment.user.name %>
            <% end %>
          </div>
          <div class="col-md-6">
            <%= comment.comment %>
          </div>
          <% if comment.user == current_user %>
            <div class="col-md-2">
              <%= link_to 'Destroy', book_book_comment_path(@book, comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-sm btn-danger" %>
            </div>
          <% end %>
        </div>
      <% end %>
      
      <%= form_with(model: [ @book, @book.book_comments.build ], local: true) do |form| %>
        <div class="field">
          <%= form.label :comment %><br>
          <%= form.text_area :comment %>
        </div>
        <div class="actions">
          <%= form.submit "送信" %>
        </div>
      <% end %>
    </div>
  </div>
</div>