rails6-bookers2-debug-ruby3-main/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get 'search' => 'searches#search'
  get 'sort_books', to: 'books#sort_by_likes', defaults: { format: :js }

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :chat_rooms, only: [:show] do
    resources :chat_messages, only: [:create]
  end
end

rails6-bookers2-debug-ruby3-main/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  scope :with_recent_favorites_count, -> {
    left_joins(:favorites)
         .group('books.id')
         .order('COUNT(favorites.id) DESC, books.created_at DESC')
  }
end

rails6-bookers2-debug-ruby3-main/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

rails6-bookers2-debug-ruby3-main/app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :content, length: { maximum: 140 }
end

rails6-bookers2-debug-ruby3-main/app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :users, through: :chat_room_users
  has_many :chat_messages
end

rails6-bookers2-debug-ruby3-main/app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

rails6-bookers2-debug-ruby3-main/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: { scope: :book_id }
end

rails6-bookers2-debug-ruby3-main/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

rails6-bookers2-debug-ruby3-main/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
    def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

rails6-bookers2-debug-ruby3-main/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @books_comment = BookComment.new
    @book.increment!(:views_count)
  end

  def index
    @books = Book.with_recent_favorites_count
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      flash.now[:error] = @book.errors.full_messages.join('/')
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      flash.now[:error] = @book.errors.full_messages.join('/')
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "Book was successfully deleted."
  end
  
  def sort_by_likes
   @books = Book.with_recent_favorites_count
    respond_to do |format|
      format.js { render 'index' }
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path, alert: "You are not authorized to edit this book."
    end
  end
end

rails6-bookers2-debug-ruby3-main/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

rails6-bookers2-debug-ruby3-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find_by(id: params[:id])
    if @user
      @books = @user.books
      @book = Book.new
      @is_mutual_follow = current_user.following?(@user) && @user.following?(current_user)
    else
      redirect_to root_path, alert: "User not found."
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      p 'success'
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      flash.now[:error] = @user.errors.full_messages
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :title)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

rails6-bookers2-debug-ruby3-main/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

rails6-bookers2-debug-ruby3-main/app/helpers/books_helper.rb
module BooksHelper
end

rails6-bookers2-debug-ruby3-main/app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

rails6-bookers2-debug-ruby3-main/app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

rails6-bookers2-debug-ruby3-main/app/helpers/favorites_helper.rb
module FavoritesHelper
end

rails6-bookers2-debug-ruby3-main/app/helpers/homes_helper.rb
module HomesHelper
end

rails6-bookers2-debug-ruby3-main/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

rails6-bookers2-debug-ruby3-main/app/helpers/searches_helper.rb
module SearchesHelper
end

rails6-bookers2-debug-ruby3-main/app/helpers/users_helper.rb
module UsersHelper
end

rails6-bookers2-debug-ruby3-main/app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

rails6-bookers2-debug-ruby3-main/app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

rails6-bookers2-debug-ruby3-main/app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="search-container">
    <% if user_signed_in? %>
      <%= form_with url: search_path, method: :get, local: true, class: 'search-form' do %>
        <div>
          <%= text_field_tag :content, params[:content], placeholder: '検索' %>
          <%= select_tag :model, options_for_select([['User', 'user'], ['Book', 'book']]) %>
          <%= select_tag :method, options_for_select([['完全一致', 'perfect'], ['前方一致', 'forward'], ['後方一致', 'backward'], ['部分一致', 'partial']]) %>
          <%= submit_tag '検索' %>
        </div>
      <% end %>
    <% end %>
  </div>
</header>

rails6-bookers2-debug-ruby3-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/2710e72808.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" media="all" href="/assets/application.css">
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
      </main>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>