rails6-bookers2-debug-ruby3-main/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get 'search' => 'searches#search'
  get 'sort_books', to: 'books#sort_by_likes', defaults: { format: :js }

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :chat_rooms, only: [:show] do
    resources :chat_messages, only: [:create]
  end
end

rails6-bookers2-debug-ruby3-main/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
    def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

rails6-bookers2-debug-ruby3-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find_by(id: params[:id])
    if @user
      @books = @user.books
      @book = Book.new
      @is_mutual_follow = current_user.following?(@user) && @user.following?(current_user)
    else
      redirect_to root_path, alert: "User not found."
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      p 'success'
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      flash.now[:error] = @user.errors.full_messages
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :title)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

rails6-bookers2-debug-ruby3-main/app/helpers/users_helper.rb
module UsersHelper
end

rails6-bookers2-debug-ruby3-main/app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>
          <% if current_user.id != user.id %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete %>
            <% else %>
              <%= link_to 'フォローする', relationships_path(followed_id: user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails6-bookers2-debug-ruby3-main/app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= user.following.count %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= user.followers.count %></th>
  </tr>
    <tr>
      <% if current_user.id != user.id %>
        <th>
          <% if current_user.following?(user) %>
            <%= link_to 'フォローを外す', relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete %>
          <% else %>
            <%= link_to 'フォローする', relationships_path(followed_id: user.id), method: :post %>
          <% end %>
          <% if current_user.following?(user) && user.following?(current_user) %>
            <% chat_room = ChatRoom.joins(:chat_room_users).where(chat_room_users: { user_id: [current_user.id, user.id] }).distinct.first_or_create %>
            <%= link_to 'チャットを始める', chat_room_path(chat_room) %>
          <% end %>
        </th>
    </tr>
  <% end %>

</table>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

rails6-bookers2-debug-ruby3-main/app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
     <% if flash.now[:error] %>
        <div class="alert alert-danger">
          <%= flash.now[:error] %>
        </div>
      <% end %>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

rails6-bookers2-debug-ruby3-main/app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render '/books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

rails6-bookers2-debug-ruby3-main/app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>